# Release Notes Configuration Template
# This file allows customization of the automated release notes generation

# Commit type mappings - customize how different commit types are transformed
commit_types:
  feat:
    label: "🆕 New Features"
    transform: "Added {description}"
  fix:
    label: "🐛 Bug Fixes"
    transform: "Fixed {description}"
  perf:
    label: "🔧 Improvements"
    transform: "Improved performance of {description}"
  refactor:
    label: "🔧 Improvements"
    transform: "Refactored {description} for better maintainability"
  style:
    label: "🎨 UI/UX Improvements"
    transform: "Updated styling for {description}"
  docs:
    label: "📚 Documentation"
    transform: "Updated documentation for {description}"
    include: false # Set to true to include docs changes in release notes
  test:
    label: "🧪 Testing"
    transform: "Added tests for {description}"
    include: false # Set to true to include test changes in release notes
  build:
    label: "🔧 Improvements"
    transform: "Improved build process and deployment"
    include: false # Set to true to include build changes in release notes
  ci:
    label: "🔧 Improvements"
    transform: "Improved continuous integration"
    include: false # Set to true to include CI changes in release notes
  chore:
    label: "🔧 Improvements"
    transform: "Updated dependencies and maintenance tasks"
    include: false # Set to true to include chore changes in release notes

# Custom section order (sections will appear in this order)
section_order:
  - "🚨 Breaking Changes"
  - "🆕 New Features"
  - "🎨 UI/UX Improvements"
  - "🔧 Improvements"
  - "🐛 Bug Fixes"
  - "📚 Documentation"
  - "🧪 Testing"
  - "📝 Other Changes"

# Custom templates for different platforms
templates:
  # Template for mobile app releases
  mobile:
    header: |
      ## What's New in Flow Reference Wallet {version}

      Thank you for using Flow Reference Wallet! Here's what's new in this release:
    footer: |

      ---

      ### Download
      - 📱 [iOS App Store](https://apps.apple.com/app/flow-reference-wallet)
      - 🤖 [Google Play Store](https://play.google.com/store/apps/details?id=com.flowfoundation.wallet)

      **Full Changelog**: https://github.com/{repo}/compare/{previous_tag}...{tag}

  # Template for browser extension releases
  extension:
    header: |
      ## Flow Reference Wallet Extension {version}

      New updates for the Flow Reference Wallet browser extension:
    footer: |

      ---

      ### Install Extension
      - 🌐 [Chrome Web Store](https://chrome.google.com/webstore/detail/flow-reference-wallet)
      - 🦊 Firefox Add-ons (Coming Soon)

      **Full Changelog**: https://github.com/{repo}/compare/{previous_tag}...{tag}

# Exclude patterns - commits matching these patterns will be excluded
exclude_patterns:
  - "^Merge"
  - "^Revert"
  - "^chore: release"
  - "^docs: update"
  - "^test:"
  - "^ci:"
  - "^build:"

# Custom emoji mappings for different scopes
scope_emojis:
  ui: "🎨"
  auth: "🔐"
  wallet: "💰"
  transaction: "💸"
  security: "🔒"
  performance: "⚡"
  api: "🔌"
  database: "🗄️"
  mobile: "📱"
  extension: "🌐"
  core: "⚙️"

# Language-specific transformations (future enhancement)
languages:
  en:
    breaking_changes: "🚨 Breaking Changes"
    new_features: "🆕 New Features"
    improvements: "🔧 Improvements"
    bug_fixes: "🐛 Bug Fixes"
    other_changes: "📝 Other Changes"
