/**
 * Random username generator utility
 * Generates usernames using combinations of fruits, animals, nature words, and adjectives
 * Format: three words (no digits)
 */

const fruits = [
  'Apple',
  'Apricot',
  'Avocado',
  'Banana',
  'Cherry',
  'Coconut',
  'Date',
  'Fig',
  'Grape',
  'Guava',
  'Kiwi',
  'Lemon',
  'Lime',
  'Mango',
  'Melon',
  'Orange',
  'Papaya',
  'Peach',
  'Pear',
  'Plum',
  'Pomelo',
  'Quince',
  'Soursop',
  'Currant',
  'Sapote',
  'Longan',
  'Durian',
  'Kumquat',
  'Lychee',
  'Acai',
  'Berry',
  'Citrus',
  'Olive',
  'Raisin',
  'Prune',
  'Cassia',
  'Yuzu',
];

const animals = [
  'Ant',
  'Bear',
  'Beaver',
  'Bee',
  'Bird',
  'Bobcat',
  'Buffalo',
  'Camel',
  'Cat',
  'Cheetah',
  'Chicken',
  'Cobra',
  'Cow',
  'Crab',
  'Deer',
  'Dog',
  'Dolphin',
  'Duck',
  'Eagle',
  'Falcon',
  'Ferret',
  'Fish',
  'Fox',
  'Frog',
  'Giraffe',
  'Goat',
  'Goose',
  'Hamster',
  'Hawk',
  'Hippo',
  'Horse',
  'Jaguar',
  'Koala',
  'Lemur',
  'Leopard',
  'Lion',
  'Lizard',
  'Llama',
  'Lobster',
  'Monkey',
  'Moose',
  'Mouse',
  'Octopus',
  'Otter',
  'Owl',
  'Panda',
  'Panther',
  'Parrot',
  'Penguin',
  'Pig',
  'Rabbit',
  'Raccoon',
  'Ram',
  'Rat',
  'Raven',
  'Seal',
  'Shark',
  'Sheep',
  'Skunk',
  'Sloth',
  'Snail',
  'Snake',
  'Spider',
  'Tiger',
  'Toad',
  'Turtle',
  'Whale',
  'Wolf',
  'Wombat',
  'Zebra',
  'Badger',
  'Bat',
  'Beetle',
  'Bison',
  'Boar',
  'Caribou',
  'Clam',
  'Coyote',
  'Crow',
  'Donkey',
  'Eel',
  'Emu',
  'Firefly',
  'Gazelle',
  'Gecko',
  'Gopher',
  'Grouse',
  'Heron',
  'Hyena',
  'Iguana',
  'Jackal',
  'Jay',
  'Koi',
  'Lark',
  'Lynx',
  'Magpie',
  'Mallard',
  'Mantis',
  'Mink',
  'Mole',
  'Moth',
  'Narwhal',
  'Newt',
  'Ocelot',
  'Orca',
  'Pelican',
  'Pigeon',
  'Quail',
  'Robin',
  'Rooster',
  'Salmon',
  'Sardine',
  'Sealion',
  'Shrimp',
  'Swan',
  'Termite',
  'Toucan',
  'Trout',
  'Vulture',
  'Walrus',
  'Weasel',
  'Yak',
  'Zebu',
  'Alpaca',
  'Condor',
  'Finch',
  'Hornet',
  'Meerkat',
  'Osprey',
  'Possum',
  'Puffin',
  'Shrew',
  'Viper',
  'Wasp',
  'Wren',
  'Corgi',
  'Husky',
  'Puma',
  'Ibis',
  'Crane',
  'Stork',
  'Hound',
  'Dingo',
  'Betta',
  'Cicada',
  'Marlin',
  'Cougar',
];

const nature = [
  'River',
  'Ocean',
  'Sky',
  'Cloud',
  'Rain',
  'Sun',
  'Moon',
  'Star',
  'Comet',
  'Breeze',
  'Storm',
  'Forest',
  'Tree',
  'Leaf',
  'Rock',
  'Stone',
  'Pebble',
  'Hill',
  'Valley',
  'Canyon',
  'Desert',
  'Sand',
  'Wave',
  'Tide',
  'Lake',
  'Pond',
  'Stream',
  'Coral',
  'Reef',
  'Glacier',
  'Aurora',
  'Shadow',
  'Light',
  'Flame',
  'Fire',
  'Smoke',
  'Mist',
  'Dawn',
  'Dusk',
  'Sunset',
  'Sunrise',
  'Field',
  'Garden',
  'Flower',
  'Petal',
  'Vine',
  'Root',
  'Branch',
  'Seed',
  'Berry',
  'Moss',
  'Fern',
  'Willow',
  'Oak',
  'Pine',
  'Maple',
  'Cedar',
  'Meadow',
  'Prairie',
  'Savanna',
  'Jungle',
  'Island',
  'Lagoon',
  'Bay',
  'Shore',
  'Cave',
  'Cliff',
  'Crystal',
  'Gem',
  'Amber',
  'Pearl',
  'Quartz',
  'Emerald',
  'Topaz',
  'Volcano',
  'Geyser',
  'Thunder',
  'Horizon',
  'Echo',
  'Boulder',
  'Dune',
  'Frost',
  'Galaxy',
  'Orbit',
  'Planet',
  'Meteor',
  'Cosmos',
  'Fjord',
  'Grove',
  'Glade',
  'Bluff',
  'Delta',
  'Estuary',
  'Peak',
  'Ridge',
  'Ravine',
  'Butte',
  'Mesa',
  'Cove',
  'Inlet',
  'Grotto',
  'Cavern',
  'Knoll',
  'Dale',
  'Glen',
  'Heath',
  'Moor',
  'Fen',
  'Bog',
  'Marsh',
  'Swamp',
  'Basin',
  'Oasis',
  'Tundra',
  'Steppe',
  'Taiga',
  'Vale',
  'Blaze',
  'Ember',
  'Spark',
  'Ash',
  'Cinder',
  'Flare',
  'Glow',
  'Beam',
  'Ray',
  'Haze',
  'Fog',
  'Dew',
  'Rime',
  'Snow',
  'Hail',
  'Sleet',
  'Gust',
  'Gale',
  'Zephyr',
  'Squall',
  'Tempest',
  'Cyclone',
  'Nebula',
  'Quasar',
  'Pulsar',
  'Nova',
  'Void',
  'Abyss',
  'Zenith',
  'Nadir',
  'Eclipse',
];

const adjectives = [
  'Brave',
  'Calm',
  'Clever',
  'Cool',
  'Cozy',
  'Curious',
  'Daring',
  'Eager',
  'Fancy',
  'Gentle',
  'Glowing',
  'Golden',
  'Happy',
  'Humble',
  'Jolly',
  'Kind',
  'Lively',
  'Lucky',
  'Mellow',
  'Mighty',
  'Noble',
  'Playful',
  'Polite',
  'Proud',
  'Quick',
  'Quiet',
  'Radiant',
  'Shiny',
  'Silly',
  'Smart',
  'Smiling',
  'Snug',
  'Sparkly',
  'Swift',
  'Tiny',
  'Vibrant',
  'Warm',
  'Witty',
  'Zany',
  'Bright',
  'Bold',
  'Dynamic',
  'Epic',
  'Fierce',
  'Gleeful',
  'Joyful',
  'Lovely',
  'Merry',
  'Neat',
  'Peppy',
  'Plucky',
  'Posh',
  'Relaxed',
  'Serene',
  'Smooth',
  'Spunky',
  'Sunny',
  'Sweet',
  'Thrifty',
  'Tricky',
  'Upbeat',
  'Valiant',
  'Zealous',
  'Alert',
  'Astute',
  'Chill',
  'Crisp',
  'Dapper',
  'Keen',
  'Lush',
  'Perky',
  'Poised',
  'Prime',
  'Pure',
  'Rare',
  'Robust',
  'Sage',
  'Sharp',
  'Sleek',
  'Snappy',
  'Solid',
  'Spry',
  'Stable',
  'Steady',
  'Stealth',
  'Stern',
  'Stout',
  'Suave',
  'Super',
  'Tender',
  'Tidy',
  'True',
  'Trusty',
  'Ultra',
  'Unique',
  'Upright',
  'Urbane',
  'Vivid',
  'Wary',
  'Wild',
  'Wise',
  'Agile',
  'Blessed',
  'Caring',
  'Cosmic',
  'Crafty',
  'Divine',
  'Elated',
  'Fluent',
  'Fresh',
  'Gifted',
  'Grand',
  'Heroic',
  'Honest',
  'Ideal',
];

const allWords = [...fruits, ...animals, ...nature, ...adjectives];

/**
 * Generates a secure random integer between 0 (inclusive) and maxExclusive (exclusive)
 * Uses crypto.getRandomValues for cryptographically secure randomness
 */
function secureRandomInt(maxExclusive: number): number {
  // For React Native, we need to check if crypto.getRandomValues is available
  // If not, fall back to Math.random (less secure but works everywhere)
  if (typeof crypto !== 'undefined' && crypto.getRandomValues) {
    const array = new Uint32Array(1);
    crypto.getRandomValues(array);
    return array[0] % maxExclusive;
  }
  // Fallback for environments without crypto.getRandomValues
  return Math.floor(Math.random() * maxExclusive);
}

/**
 * Picks a random element from an array
 */
function pick<T>(arr: T[]): T {
  return arr[secureRandomInt(arr.length)];
}

/**
 * Generates a random username using three words
 * Format: [adjective]word1word2word3 or word1word2word3
 * If any word is an adjective, it's placed first
 * Avoids repeating the same word
 * Ensures username is between 3-20 characters as required by the API
 *
 * @returns A randomly generated username string (3-20 characters)
 */
export function generateRandomUsername(): string {
  // Filter to only short words (max 7 chars) to ensure 3 words fit in 20 chars
  const shortWords = allWords.filter((word) => word.length <= 7);

  let username = '';
  let attempts = 0;
  const maxAttempts = 100;

  // Keep trying until we get a valid username (3-20 chars)
  while (attempts < maxAttempts) {
    const word1 = pick(shortWords);
    let word2 = pick(shortWords);
    // Avoid repeating the same word
    while (word2 === word1) {
      word2 = pick(shortWords);
    }

    let word3 = pick(shortWords);
    // Avoid repeating words
    while (word3 === word1 || word3 === word2) {
      word3 = pick(shortWords);
    }

    // Check if any word is an adjective
    const words = [word1, word2, word3];
    const adjectiveIndex = words.findIndex((word) => adjectives.includes(word));

    if (adjectiveIndex !== -1) {
      // Put adjective first, then the other two words
      const adjective = words[adjectiveIndex];
      const otherWords = words.filter((_, index) => index !== adjectiveIndex);
      username = `${adjective}${otherWords[0]}${otherWords[1]}`;
    } else {
      // No adjective, just concatenate in order
      username = `${word1}${word2}${word3}`;
    }

    // Check if username meets length requirements (3-20 chars)
    if (username.length >= 3 && username.length <= 20) {
      return username;
    }

    attempts++;
  }

  // Fallback: if we somehow couldn't generate a valid username, use first 3 short words
  const fallback = shortWords.slice(0, 3).join('');
  return fallback.substring(0, 20); // Ensure max 20 chars
}
