version: 2.1

orbs:
  node: circleci/node@6.1.0

executors:
  macos-executor:
    macos:
      xcode: "15.4.0"
    resource_class: macos.m1.large.gen1
    working_directory: ~/project

commands:
  setup-project:
    steps:
      - checkout
      - run:
          name: Init submodules
          command: |
            git submodule sync --recursive
            git submodule update --init --recursive
      - run:
          name: Enable Corepack and install pnpm
          command: |
            corepack enable
            if [ -n "${PNPM_VERSION:-}" ]; then
              corepack prepare "pnpm@${PNPM_VERSION}" --activate
            else
              corepack prepare pnpm@latest --activate
            fi
      - run:
          name: Install JS dependencies
          command: |
            cd apps/react-native
            pnpm install --frozen-lockfile
      - run:
          name: Install Ruby gems & CocoaPods
          command: |
            cd apps/react-native/ios
            gem install bundler -N || true
            bundle install
            bundle exec pod install --repo-update
  setup-ios-signing:
    steps:
      - run:
          name: Install iOS certificates and provisioning profile
          command: |
            security create-keychain -p "$KEYCHAIN_PASSWORD" temp.keychain
            security default-keychain -s temp.keychain
            security unlock-keychain -p "$KEYCHAIN_PASSWORD" temp.keychain
            security set-keychain-settings -t 3600 -u temp.keychain

            # Import P12 cert
            echo "$IOS_CERT_P12_BASE64" | base64 --decode > cert.p12
            security import cert.p12 -k temp.keychain -P "$IOS_CERT_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
            security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" temp.keychain

            # Install provisioning profile
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            echo "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode > "~/Library/MobileDevice/Provisioning Profiles/profile.mobileprovision"

jobs:
  build-ios-beta:
    executor: macos-executor
    environment:
      IOS_WORKSPACE: FRW.xcworkspace
      IOS_SCHEME: FlowWallet-dev
      IOS_CONFIGURATION: Debug
    steps:
      - setup-project
      - setup-ios-signing
      - run:
          name: Bundle React Native (iOS)
          command: |
            cd apps/react-native
            pnpm run bundle:ios
      - run:
          name: Build & Upload to TestFlight (fastlane beta)
          command: |
            cd apps/react-native/ios
            bundle exec fastlane ios beta
      - store_artifacts:
          path: apps/react-native/ios/build
          destination: ios-build-artifacts

  build-ios-release:
    executor: macos-executor
    environment:
      IOS_WORKSPACE: FRW.xcworkspace
      IOS_SCHEME: FlowWallet
      IOS_CONFIGURATION: Release
    steps:
      - setup-project
      - setup-ios-signing
      - run:
          name: Bundle React Native (iOS)
          command: |
            cd apps/react-native
            pnpm run bundle:ios
      - run:
          name: Build & Upload to App Store (fastlane release)
          command: |
            cd apps/react-native/ios
            bundle exec fastlane ios release
      - store_artifacts:
          path: apps/react-native/ios/build
          destination: ios-build-artifacts

workflows:
  ios-beta:
    jobs:
      - build-ios-beta:
          context:
            - frw-ios-dev

  ios-release:
    jobs:
      - build-ios-release:
          context:
            - frw-ios-prod
