name: VerifyIssue

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  link-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Detect issue from branch and update PR body
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return;

            const branch = pr.head.ref || '';
            const mainBranches = ['main', 'master', 'dev', 'develop'];
            if (mainBranches.includes(branch)) return;
            if (branch.startsWith('hotfix/') || branch.startsWith('release/')) return; // don't auto-close for maintenance branches

            // Extract issue number from common patterns
            const patterns = [
              /^(\d+)-/,       // 123-feature
              /-(\d+)$/,       // feature-123
              /\/(\d+)-/,     // dev/123-feature
              /\/(\d+)$/,     // dev/123
              /^[a-z]+\/[a-z]+-(\d+)/, // feature/abc-123
            ];
            let issue = null;
            for (const re of patterns) {
              const m = branch.match(re);
              if (m) { issue = m[1]; break; }
            }
            if (!issue) return;

            let body = pr.body || '';
            const exact = new RegExp(`(^|\n)Closes #${issue}(\n|$)`, 'i');
            if (exact.test(body)) {
              core.info(`PR body already links issue #${issue}`);
              return;
            }

            // 1) Replace placeholder like "Closes #" or "Closes #<wrong>" in template's Related Issues section
            const placeholder = /(^|\n)Closes #\s*($|\n)/i;
            if (placeholder.test(body)) {
              body = body.replace(placeholder, (_m, pre, _post) => `${pre}Closes #${issue}\n`);
            } else {
              // 2) If "## 🔗 Related Issues" exists, insert under it
              const relatedHeader = /(##\s*🔗\s*Related Issues\s*\n+)/i;
              if (relatedHeader.test(body)) {
                body = body.replace(relatedHeader, (m) => `${m}Closes #${issue}\n\n`);
              } else {
                // 3) Fallback: append to end
                body = (body.trim() + `\n\nCloses #${issue}`).trim() + "\n";
              }
            }

            // Ensure single line: remove duplicate "Closes #<issue>" if any
            const lines = body.split(/\r?\n/);
            const seen = new Set();
            const deduped = lines.filter((ln) => {
              const m = ln.match(/^\s*Closes\s+#(\d+)\s*$/i);
              if (!m) return true;
              const key = `closes-${m[1]}`;
              if (seen.has(key)) return false;
              seen.add(key);
              return true;
            }).join("\n");

            const newBody = deduped;
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              body: newBody,
            });
            core.notice(`Linked PR #${pr.number} to issue #${issue}`);

  verify-linked-issue:
    runs-on: ubuntu-latest
    needs: link-issue
    if: >-
      !startsWith(github.event.pull_request.head.ref, 'hotfix/') &&
      !startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Ensure Pull Request has a linked issue.
        uses: outblock/verify-linked-issue-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
